//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMerge.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelMerge.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Extract Diff.
        /// </summary>
        public static string Button_ExtractDiff {
            get {
                return ResourceManager.GetString("Button_ExtractDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Log.
        /// </summary>
        public static string ContextMenu_BuildCellBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildCellBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Column Base Log.
        /// </summary>
        public static string ContextMenu_BuildColumnBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildColumnBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Row Base Log.
        /// </summary>
        public static string ContextMenu_BuildRowBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildRowBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy as CSV.
        /// </summary>
        public static string ContextMenu_CopyAsCsv {
            get {
                return ResourceManager.GetString("ContextMenu_CopyAsCsv", resourceCulture);
            }
        }

        /// <summary>
        ///   Copy as TSV.
        /// </summary>
        public static string ContextMenu_CopyAsTsv {
            get {
                return ResourceManager.GetString("ContextMenu_CopyAsTsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract diff with this row as column header..
        /// </summary>
        public static string ContextMenu_DiffAsHeader {
            get {
                return ResourceManager.GetString("ContextMenu_DiffAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑Reset Column Header.
        /// </summary>
        public static string ContextMenu_ResetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ←Reset Row Header.
        /// </summary>
        public static string ContextMenu_ResetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑Set Column Header.
        /// </summary>
        public static string ContextMenu_SetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ←Set Row Header.
        /// </summary>
        public static string ContextMenu_SetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${LEFT} → ${RIGHT}.
        /// </summary>
        public static string DefaultColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed &quot;${ROW}&quot;&apos;s &quot;${COL}&quot; to &quot;${RIGHT}&quot; from &quot;${LEFT}&quot;.
        /// </summary>
        public static string DefaultLogFormat {
            get {
                return ResourceManager.GetString("DefaultLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;${ROW}&quot; was added..
        /// </summary>
        public static string DefaultLogFormatAddedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatAddedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;${ROW}&quot; was removed..
        /// </summary>
        public static string DefaultLogFormatRemovedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatRemovedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${LEFT} → ${RIGHT}.
        /// </summary>
        public static string DefaultRowBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultRowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Behavior.
        /// </summary>
        public static string GroupBox_Behavior {
            get {
                return ResourceManager.GetString("GroupBox_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Format.
        /// </summary>
        public static string GroupBox_DisplayFormat {
            get {
                return ResourceManager.GetString("GroupBox_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Format.
        /// </summary>
        public static string GroupBox_LogFormat {
            get {
                return ResourceManager.GetString("GroupBox_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Setting.
        /// </summary>
        public static string GroupBox_ReadSetting {
            get {
                return ResourceManager.GetString("GroupBox_ReadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Style.
        /// </summary>
        public static string GroupBox_Style {
            get {
                return ResourceManager.GetString("GroupBox_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Color.
        /// </summary>
        public static string Label_AddedColor {
            get {
                return ResourceManager.GetString("Label_AddedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Row Log Format.
        /// </summary>
        public static string Label_AddedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_AddedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Rows({0}).
        /// </summary>
        public static string Label_AddedRows {
            get {
                return ResourceManager.GetString("Label_AddedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always expand cell diff.
        /// </summary>
        public static string Label_AlwaysExpandCellDiff {
            get {
                return ResourceManager.GetString("Label_AlwaysExpandCellDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Modified Row.
        /// </summary>
        public static string Label_ColorModifiedRow {
            get {
                return ResourceManager.GetString("Label_ColorModifiedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Base Log Format.
        /// </summary>
        public static string Label_ColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_ColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Header Color.
        /// </summary>
        public static string Label_ColumnHeaderColor {
            get {
                return ResourceManager.GetString("Label_ColumnHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Width.
        /// </summary>
        public static string Label_ColumnWidth {
            get {
                return ResourceManager.GetString("Label_ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit Cell Height.
        /// </summary>
        public static string Label_FitRowHeight {
            get {
                return ResourceManager.GetString("Label_FitRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus first diff when extracted.
        /// </summary>
        public static string Label_FocusFirstDiff {
            get {
                return ResourceManager.GetString("Label_FocusFirstDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore File Setting.
        /// </summary>
        public static string Label_IgnoreFileSetting {
            get {
                return ResourceManager.GetString("Label_IgnoreFileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Cell Log Format.
        /// </summary>
        public static string Label_LogFormat {
            get {
                return ResourceManager.GetString("Label_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Row Height.
        /// </summary>
        public static string Label_MaxRowHeight {
            get {
                return ResourceManager.GetString("Label_MaxRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Row Height.
        /// </summary>
        public static string Label_MinRowHeight {
            get {
                return ResourceManager.GetString("Label_MinRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Cells({0}).
        /// </summary>
        public static string Label_ModifiedCells {
            get {
                return ResourceManager.GetString("Label_ModifiedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Color.
        /// </summary>
        public static string Label_ModifiedColor {
            get {
                return ResourceManager.GetString("Label_ModifiedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Row Color.
        /// </summary>
        public static string Label_ModifiedRowColor {
            get {
                return ResourceManager.GetString("Label_ModifiedRowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Rows({0}).
        /// </summary>
        public static string Label_ModifiedRows {
            get {
                return ResourceManager.GetString("Label_ModifiedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show dialog if no diff.
        /// </summary>
        public static string Label_NotifyEqual {
            get {
                return ResourceManager.GetString("Label_NotifyEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Color.
        /// </summary>
        public static string Label_RemovedColor {
            get {
                return ResourceManager.GetString("Label_RemovedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Row Log Format.
        /// </summary>
        public static string Label_RemovedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_RemovedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Rows({0}).
        /// </summary>
        public static string Label_RemovedRows {
            get {
                return ResourceManager.GetString("Label_RemovedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Base Log Format.
        /// </summary>
        public static string Label_RowBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_RowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Colors.
        /// </summary>
        public static string Label_RowColor {
            get {
                return ResourceManager.GetString("Label_RowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Color.
        /// </summary>
        public static string Label_RowHeaderColor {
            get {
                return ResourceManager.GetString("Label_RowHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Height.
        /// </summary>
        public static string Label_RowlHeight {
            get {
                return ResourceManager.GetString("Label_RowlHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank columns.
        /// </summary>
        public static string Label_SkipFirstBlankColumns {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank rows.
        /// </summary>
        public static string Label_SkipFirstBlankRows {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim last blank columns.
        /// </summary>
        public static string Label_TrimLastBlankColumns {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim last blank rows.
        /// </summary>
        public static string Label_TrimLastBlankRows {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Console.
        /// </summary>
        public static string MenuItem_Console {
            get {
                return ResourceManager.GetString("MenuItem_Console", resourceCulture);
            }
        }

        /// <summary>
        ///   Refresh.
        /// </summary>
        public static string MenuItem_Refresh {
            get {
                return ResourceManager.GetString("MenuItem_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Execute external command.
        /// </summary>
        public static string MenuItem_ExeExternalCmd {
            get {
                return ResourceManager.GetString("MenuItem_ExeExternalCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands.
        /// </summary>
        public static string MenuItem_ExternalCommands {
            get {
                return ResourceManager.GetString("MenuItem_ExternalCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Settings.
        /// </summary>
        public static string MenuItem_FileSettings {
            get {
                return ResourceManager.GetString("MenuItem_FileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Setting.
        /// </summary>
        public static string MenuItem_GeneralSetting {
            get {
                return ResourceManager.GetString("MenuItem_GeneralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Dst File.
        /// </summary>
        public static string MenuItem_OpenAsDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Src File.
        /// </summary>
        public static string MenuItem_OpenAsSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open dst File.
        /// </summary>
        public static string MenuItem_OpenDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open src file.
        /// </summary>
        public static string MenuItem_OpenSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Files.
        /// </summary>
        public static string MenuItem_RecentFiles {
            get {
                return ResourceManager.GetString("MenuItem_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent File Sets.
        /// </summary>
        public static string MenuItem_RecentFileSets {
            get {
                return ResourceManager.GetString("MenuItem_RecentFileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View.
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no difference..
        /// </summary>
        public static string Message_NoDiff {
            get {
                return ResourceManager.GetString("Message_NoDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart to apply the changes..
        /// </summary>
        public static string Message_Reboot {
            get {
                return ResourceManager.GetString("Message_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting Diff ....
        /// </summary>
        public static string Msg_ExtractingDiff {
            get {
                return ResourceManager.GetString("Msg_ExtractingDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet index of the applied file settings is out of range.
        ///Will use first sheet.
        ///If you don&apos;t want to apply file settings, enable &quot;Ignore File Setting&quot;..
        /// </summary>
        public static string Msg_OutofSheetRange {
            get {
                return ResourceManager.GetString("Msg_OutofSheetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Files ....
        /// </summary>
        public static string Msg_ReadingFiles {
            get {
                return ResourceManager.GetString("Msg_ReadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not be displayed.
        /// </summary>
        public static string Msg_Undisplayable {
            get {
                return ResourceManager.GetString("Msg_Undisplayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are too many records. Display only around diff..
        /// </summary>
        public static string Msg_WarnSize {
            get {
                return ResourceManager.GetString("Msg_WarnSize", resourceCulture);
            }
        }

        /// <summary>
        ///   All.
        /// </summary>
        public static string RadioButton_ShowAll {
            get {
                return ResourceManager.GetString("RadioButton_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only Diff.
        /// </summary>
        public static string RadioButton_ShowOnlyDiff {
            get {
                return ResourceManager.GetString("RadioButton_ShowOnlyDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Down.
        /// </summary>
        public static string Shortcut_Ctrl_Down {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + I.
        /// </summary>
        public static string Shortcut_Ctrl_I {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + K.
        /// </summary>
        public static string Shortcut_Ctrl_K {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + L.
        /// </summary>
        public static string Shortcut_Ctrl_L {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Left.
        /// </summary>
        public static string Shortcut_Ctrl_Left {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + O.
        /// </summary>
        public static string Shortcut_Ctrl_O {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Right.
        /// </summary>
        public static string Shortcut_Ctrl_Right {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Up.
        /// </summary>
        public static string Shortcut_Ctrl_Up {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F8.
        /// </summary>
        public static string Shortcut_F8 {
            get {
                return ResourceManager.GetString("Shortcut_F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F9.
        /// </summary>
        public static string Shortcut_F9 {
            get {
                return ResourceManager.GetString("Shortcut_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit External Command.
        /// </summary>
        public static string Title_ExternalCommandEditorWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands.
        /// </summary>
        public static string Title_ExternalCommandsWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit File Setting.
        /// </summary>
        public static string Title_FileSettingEditorWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Settings.
        /// </summary>
        public static string Title_FileSettingsWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Settings.
        /// </summary>
        public static string Title_GeneralSettingWindow {
            get {
                return ResourceManager.GetString("Title_GeneralSettingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File Path.
        /// </summary>
        public static string ToolTip_DstFilePath {
            get {
                return ResourceManager.GetString("ToolTip_DstFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst Sheet.
        /// </summary>
        public static string ToolTip_DstSheet {
            get {
                return ResourceManager.GetString("ToolTip_DstSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File Path.
        /// </summary>
        public static string ToolTip_SrcFilePath {
            get {
                return ResourceManager.GetString("ToolTip_SrcFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src Sheet.
        /// </summary>
        public static string ToolTip_SrcSheet {
            get {
                return ResourceManager.GetString("ToolTip_SrcSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap src and dst.
        /// </summary>
        public static string ToolTip_Swap {
            get {
                return ResourceManager.GetString("ToolTip_Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply.
        /// </summary>
        public static string Word_Apply {
            get {
                return ResourceManager.GetString("Word_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Args.
        /// </summary>
        public static string Word_Args {
            get {
                return ResourceManager.GetString("Word_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank.
        /// </summary>
        public static string Word_Blank {
            get {
                return ResourceManager.GetString("Word_Blank", resourceCulture);
            }
        }

        public static string ContextMenu_AcceptSrc {
            get { return ResourceManager.GetString("ContextMenu_AcceptSrc", resourceCulture); }
        }

        public static string ContextMenu_AcceptDst {
            get { return ResourceManager.GetString("ContextMenu_AcceptDst", resourceCulture); }
        }

        public static string ContextMenu_AcceptSrcRow {
            get { return ResourceManager.GetString("ContextMenu_AcceptSrcRow", resourceCulture); }
        }

        public static string ContextMenu_AcceptDstRow {
            get { return ResourceManager.GetString("ContextMenu_AcceptDstRow", resourceCulture); }
        }

        public static string Button_SaveMerge {
            get {
                return ResourceManager.GetString("Button_SaveMerge", resourceCulture);
            }
        }

        public static string Msg_NoMergeDecisions {
            get {
                return ResourceManager.GetString("Msg_NoMergeDecisions", resourceCulture);
            }
        }

        public static string Msg_MergeSaved {
            get {
                return ResourceManager.GetString("Msg_MergeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel.
        /// </summary>
        public static string Word_Chinese {
            get {
                return ResourceManager.GetString("Word_Chinese", resourceCulture);
            }
        }

        /// <summary>
        ///   Cancel.
        /// </summary>
        public static string Word_Cancel {
            get {
                return ResourceManager.GetString("Word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CaseSensitive.
        /// </summary>
        public static string Word_CaseSensitive {
            get {
                return ResourceManager.GetString("Word_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Header Index.
        /// </summary>
        public static string Word_ColumnHeaderIndex {
            get {
                return ResourceManager.GetString("Word_ColumnHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default.
        /// </summary>
        public static string Word_Default {
            get {
                return ResourceManager.GetString("Word_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done.
        /// </summary>
        public static string Word_Done {
            get {
                return ResourceManager.GetString("Word_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File.
        /// </summary>
        public static string Word_DstFile {
            get {
                return ResourceManager.GetString("Word_DstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit.
        /// </summary>
        public static string Word_Edit {
            get {
                return ResourceManager.GetString("Word_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English.
        /// </summary>
        public static string Word_English {
            get {
                return ResourceManager.GetString("Word_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExactMatch.
        /// </summary>
        public static string Word_ExactMatch {
            get {
                return ResourceManager.GetString("Word_ExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable.
        /// </summary>
        public static string Word_Executable {
            get {
                return ResourceManager.GetString("Word_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File.
        /// </summary>
        public static string Word_File {
            get {
                return ResourceManager.GetString("Word_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font.
        /// </summary>
        public static string Word_Font {
            get {
                return ResourceManager.GetString("Word_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launguage.
        /// </summary>
        public static string Word_Language {
            get {
                return ResourceManager.GetString("Word_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match Type.
        /// </summary>
        public static string Word_MatchType {
            get {
                return ResourceManager.GetString("Word_MatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Row Header Width.
        /// </summary>
        public static string Word_MaxRowHeaderWidth {
            get {
                return ResourceManager.GetString("Word_MaxRowHeaderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name.
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path.
        /// </summary>
        public static string Word_Path {
            get {
                return ResourceManager.GetString("Word_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regex.
        /// </summary>
        public static string Word_Regex {
            get {
                return ResourceManager.GetString("Word_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove.
        /// </summary>
        public static string Word_Remove {
            get {
                return ResourceManager.GetString("Word_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset.
        /// </summary>
        public static string Word_Reset {
            get {
                return ResourceManager.GetString("Word_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Index.
        /// </summary>
        public static string Word_RowHeaderIndex {
            get {
                return ResourceManager.GetString("Word_RowHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Name.
        /// </summary>
        public static string Word_RowHeaderName {
            get {
                return ResourceManager.GetString("Word_RowHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search.
        /// </summary>
        public static string Word_Search {
            get {
                return ResourceManager.GetString("Word_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting.
        /// </summary>
        public static string Word_Setting {
            get {
                return ResourceManager.GetString("Word_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet.
        /// </summary>
        public static string Word_Sheet {
            get {
                return ResourceManager.GetString("Word_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet Index.
        /// </summary>
        public static string Word_SheetIndex {
            get {
                return ResourceManager.GetString("Word_SheetIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet Name.
        /// </summary>
        public static string Word_SheetName {
            get {
                return ResourceManager.GetString("Word_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File.
        /// </summary>
        public static string Word_SrcFile {
            get {
                return ResourceManager.GetString("Word_SrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set as Startup Sheet.
        /// </summary>
        public static string Word_StartupSheet {
            get {
                return ResourceManager.GetString("Word_StartupSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool.
        /// </summary>
        public static string Word_Tool {
            get {
                return ResourceManager.GetString("Word_Tool", resourceCulture);
            }
        }
    }
}
